config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :articles
  root to: "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  after_destroy :ensure_article_count

  private

  def ensure_article_count
    return unless Article.count < 10

    # Note that the following line calls the top-level `Faker` module:
    Article.create(title: Faker::Book.title, content: Faker::Lorem.paragraph)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def index
    @articles = Article.all
  end

  def show
  end

  def new
    @article = Article.new
    @page_title = 'New Article'
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to @article, notice: 'Article was successfully created.'
    else
      render :new
    end
  end

  def edit
    @article = Article.find(params[:id])
    @page_title = 'Edit Article'
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article, notice: 'Article was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_url, notice: 'Article was successfully destroyed.'
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="d-flex justify-content-between articlecolumn">
      <%= form_with(model: @article, local: true) do |form| %>
        <div class="form-group">
          <%= form.label :title %>
          <%= form.text_field :title, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= form.label :content %>
          <%= form.text_area :content, class: "form-control" %>
        </div>
        <div class="actions">
          <%= form.submit (@article.new_record? ? 'Create Article' : 'Update Article'), class: "btn btn-primary btnsubmit" %>
        </div>
      <% end %>
      <%= link_to 'Back', articles_path %>
    </div>
  </div>

app/views/articles/edit.html.erb
<h1><%= @page_title %></h1>
<%= render "form"%>

app/views/articles/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2 articlecolumn">
      <% @articles.each do |article| %>
        <h2><%= link_to article.title, article %></h2>
        <p><%= article.content %></p>
      <% end %>
    </div>
  </div>
</div>

app/views/articles/new.html.erb
<h1><%= @page_title %></h1>
<%= render 'form' %>

app/views/articles/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2 articledescription">
      <h1><%= @article.title %>
        <%= link_to '', edit_article_path(@article), class: "fas fa-pen" %>
        <%= link_to article_path(@article), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: 'fas fa-trash' do %>
        <% end %>
      </h1>
      <hr>
      <p><%= @article.content %></p>
      <%= link_to 'Back', articles_path, class: "backbutton" %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <!-- Image and text NAVBAR -->
<nav class="navbar navbar-light bg-light">
  <a class="navbar-brand" href="/articles">
    <img src="https://d26jy9fbi4q9wx.cloudfront.net/assets/logo-ae2beeecce25d711f577b08deb9adfc6c02b673ed106b8d6c3da0f1721d9da33.svg" width="30" height="30" class="d-inline-block align-top" alt="" id="navicon">
    <strong>Wikinimous</strong>
  </a>
  <div class="d-flex">
    <a href="/articles/new" class="btn btn-primary btnnav">New Article</a>
  </div>
</nav>
    <%= yield %>
  </body>
</html>